services:
  back-end:
    image: chouaibiaymen/canvasbackend
    ports:
      - '3000:3000'
    container_name: canvasBack_Container
    volumes:
      - ./uploads:/app/uploads

    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: canvasDataBase
    networks:
      - mynetwork

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: canvasDataBase
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
