version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: production
    networks:
      - mynetwork

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: canvasback_canvasback_mysql-data2
    ports:
      - "3307:3306"
    volumes:
      - canvasback_mysql-data2:/var/lib/mysql 
    networks:
      - mynetwork

volumes:
  mysql-data:
  canvasback_mysql-data2: 

networks:
  mynetwork:
    driver: bridge
