name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./CanvasBack
        run: npm install --force

      - name: Run tests
        working-directory: ./CanvasBack
        run: npm run test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./CanvasBack
        run: docker build -t chouaibiaymen/canvasbackend:latest .
