name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'CanvasBack/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CanvasBack/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./CanvasBack
        run: npm install --force

      - name: Run tests
        working-directory: ./CanvasBack
        run: npm run test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./CanvasBack
        run: docker build -t chouaibiaymen/canvasbackend:latest .

      - name: Push Docker image
        run: docker push chouaibiaymen/canvasbackend:latest
