name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: chouaibiaymen/canvasbackend
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CanvasBack
    steps:
      - uses: actions/checkout@v4

      - name: Install node-pre-gyp globally
        run: npm install -g node-pre-gyp

      - name: Install dependencies
        run: npm i --force

      - name: Run tests filtered by user.controller
        run: npm run test user.controller

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./CanvasBack
        run: docker build -t ${{env.IMAGE_NAME}}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:

          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image docker
        run: docker push ${{env.IMAGE_NAME}}:latest

      - name: tag image with version number
        run: docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:${{github.run_number}}
      
      - name: push image with version number
        run: docker push ${{env.IMAGE_NAME}}:${{github.run_number}}

  deployement:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: connect via ssh and execute commands
        uses: appleboy/ssh-action@v1
        with:
          host: 51.178.31.158
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
               cd ~/CanvasApplication/Devops/BackEnd
               sudo docker compose pull
               sudo docker compose up -d --force-recreate --remove-orphans