name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: install dependencies
       run: npm i --force

     - name: npm run test  
       run: npm run test


  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: checkout
       uses: actions/checkout@v4 

     - name: build docker image 
       run: docker build -t chouaibiaymen/canvasbackend .
